name: Build and Deploy Static Blog to gh-pages

on:
  push:
    branches: [ main ]
    paths:
      - 'blog/**'
      - 'templates/**'
      - 'static/**'
      - 'generate.py'
      - 'requirements.txt'
      - '.github/workflows/build-site.yml'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the static site
        run: python generate.py 

      - name: Create .nojekyll file
        run: touch ./docs/.nojekyll

      # --- Deploy Step (no changes needed here) ---
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Automated build: Deploy updates to gh-pages [skip ci]'
